// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package compute

import (
	"testing"

	cai2hcl_testing "github.com/GoogleCloudPlatform/terraform-google-conversion/v2/cai2hcl/testing"
)

func TestComputeRegionBackendService(t *testing.T) {
	testFileName := "compute_region_backend_service"

	cai2hcl_testing.AssertTestFiles(
		t,
		ConverterNamesPerAssetType, AssetNameRegexpConverterPairs, ConverterMap,
		"./testdata",
		[]string{testFileName})
}
